### ISSUE TITLE
Discover

### ISSUE THREAD

**Issue by VladimirTyrin** [OPEXGroup/ITCC.Library#21]
```
Object reference not set to an instance of an object.
   at ITCC.HTTP.Server.Core.ResponseFactory.BuildResponse(HttpListenerContext context, HttpStatusCode code, Object body, IDictionary`2 additionalHeaders, Boolean alreadyEncoded) in C:\SpetsStroy\SpetsStroyDemo\ITCC.Library\ITCC.HTTP.Server\Core\ResponseFactory.cs:line 88
   at ITCC.HTTP.Server.Core.ResponseFactory.BuildResponse(HttpListenerContext context, HandlerResult handlerResult, Boolean alreadyEncoded) in C:\SpetsStroy\SpetsStroyDemo\ITCC.Library\ITCC.HTTP.Server\Core\ResponseFactory.cs:line 67
   at ITCC.HTTP.Server.Core.StaticServer`1.<OnMessage>d__36.MoveNext() in C:\SpetsStroy\SpetsStroyDemo\ITCC.Library\ITCC.HTTP.Server\Core\StaticServer.cs:line 389
```

**Comment by VladimirTyrin** [comment]
Fixed
