### ISSUE TITLE
Handle HttpListenerException

### ISSUE THREAD

**Issue by vladislav-prishchepa** [OPEXGroup/ITCC.Library#59]
Occurs suddenly when unreliable connection is using.

Log example:
```
[09.08.2017 19:32:01.496] [DEBUG] [THR 22    ] [ CREDENTIALS] New token generated for hm21
[09.08.2017 19:32:01.497] [DEBUG] [THR 22    ] [ CREDENTIALS] Successfull login from hm21 (213.87.138.113:22364).
[09.08.2017 19:32:06.380] [TRACE] [THR 22    ] [ CREDENTIALS] Token for hm23 is still alive, 22270,6925364 seconds left
[09.08.2017 19:32:08.185] [ WARN] [THR 4     ] [HTTP HANDLER] EXCEPTION (HttpListenerException)
The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpRequestStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadToEndAsyncInternal>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Digitator.Server.Core.HTTP.HandlerFactory.<ReadRequestBodyAsync>d__58.MoveNext() in C:\Users\Administrator\Source\Repos\Digitator\src\Digitator.Server.Core\HTTP\HandlerFactory.cs:line 823

[09.08.2017 19:32:08.187] [ INFO] [THR 4     ] [HTTP HANDLER] Bad request for hm23 (213.87.136.121:43579)
[09.08.2017 19:32:16.852] [TRACE] [THR 26    ] [ CREDENTIALS] Token for hm21 is still alive, 28784,6409316 seconds left
[09.08.2017 19:32:22.650] [TRACE] [THR 27    ] [ CREDENTIALS] Token for hm23 is still alive, 22254,4227579 seconds left
[09.08.2017 19:32:28.581] [ WARN] [THR 4     ] [HTTP HANDLER] EXCEPTION (HttpListenerException)
An operation was attempted on a nonexistent network connection
   at System.Net.HttpRequestStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadToEndAsyncInternal>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Digitator.Server.Core.HTTP.HandlerFactory.<ReadRequestBodyAsync>d__58.MoveNext() in C:\Users\Administrator\Source\Repos\Digitator\src\Digitator.Server.Core\HTTP\HandlerFactory.cs:line 823

[09.08.2017 19:32:28.586] [ INFO] [THR 4     ] [HTTP HANDLER] Bad request for hm23 (213.87.136.121:18379)
```

**Comment by VladimirTyrin** [comment]
Not library code
